# Generated by Django 5.1.4 on 2024-12-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome usuario")),
                ("email", models.CharField(max_length=100, verbose_name="email")),
                ("senha", models.CharField(max_length=100, verbose_name="senha")),
            ],
        ),
    ]
