# Generated by Django 5.1.4 on 2024-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titúlo da tarefa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateField(verbose_name='Data da entrega')),
                ('data_finalizacao', models.DateField(null=True)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['data_finalizacao'],
            },
        ),
    ]
