# Generated by Django 5.1.4 on 2024-12-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gerenciador_usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=100, verbose_name="Titúlo da tarefa"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_entrega", models.DateField(verbose_name="Data da entrega")),
                ("data_finalizacao", models.DateField(null=True)),
                ("email", models.CharField(max_length=100)),
                (
                    "usuario",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gerenciador_usuario.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["data_finalizacao"],
            },
        ),
    ]
