# Generated by Django 5.1.4 on 2025-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerenciador_tarefas", "0002_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(default="Descrição não fornecida"),
        ),
    ]
